### ISSUE TITLE
Teilnahme ohne Kamera

### ISSUE THREAD

**Issue by ghost** [dunlin/dunlin#3]

**Comment by ghost** [comment]
Die Ursache liegt bei der localmedia lib. Ich habe mal einen PR dort gestellt, hoffentlich wird der gemerged sonst müssen wir was selber bauen: https://github.com/otalk/localmedia/pull/6

**Comment by matthistuff** [comment]
https://trello.com/c/Z5p9A7Ya/8-join-without-camera
